name: Verify
on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Ruby gem cache
        uses: actions/cache@v2.1.0
        with:
          path: .bundle # vendor directory has special meaning in Go 1.14
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install gems
        run: |
          bundle config path .bundle
          bundle install --jobs 4 --retry 3

      - name: Run Danger
        if: "github.event_name == 'pull_request'"
        run: |
          bundle exec danger --verbose
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run linters
        run: |
          bundle exec rubocop --parallel

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.27

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Run tests and build
        run: make

      - name: Upload code coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make coverage
